export default {
  ADD_ENTITY: 'ADD_ENTITY',
  ADD_ITEM: 'ADD_ITEM',
  DESTROY_ITEM: 'DESTROY_ITEM',
  HIDE_INVENTORY: 'HIDE_INVENTORY',
  MOVE_ITEMS: 'MOVE_ITEMS',
  SET_KEY_STATE: 'SET_KEY_STATE',
  SHOW_INVENTORY: 'SHOW_INVENTORY',
  UPDATE_DEBUG_STATE: 'UPDATE_DEBUG_STATE',
}
