export {
  faBars,
  faBomb,
  faBook,
  faBug,
  faCheck,
  faCodeBranch,
  faComment,
  faComments,
  faCopy,
  faEnvelope,
  faExclamationCircle,
  faExclamationTriangle,
  faEye,
  faEyeSlash,
  faInfoCircle,
  faKey,
  faLock,
  faMapMarker,
  faPencilAlt,
  faPlus,
  faQuestionCircle,
  faSearch,
  faSignInAlt,
  faSignOutAlt,
  faSpinner,
  faThumbsUp,
  faTimes,
  faUser,
  faUserCircle,
  faUsers,
  faUserSecret,
} from '@fortawesome/free-solid-svg-icons'

export {
  faFacebook,
  faFacebookSquare,
  faInstagram,
  faKickstarter,
  faTwitter,
  faTwitterSquare,
  faYoutube,
} from '@fortawesome/free-brands-svg-icons'
